#!/bin/sh

if [ $# -ne 3 ]; then
	echo "Usage: $0 <duty1> <duty2> <serial_port>"
	exit 1
fi

echo "SSR_force_duty_cycle 0 $1" > $3
echo "SSR_force_duty_cycle 1 $2" > $3
echo "SSR_lock_duty_cycle 1" > $3

exit
